### ISSUE TITLE
Real images are not found in the dataset

### ISSUE THREAD

**Issue by Konerusudhir** [Inf-imagine/Sentry#2]
What's the goal of this dataset? 

Is it to train a binary classifier? If so, I could only find AI-generated images in the dataset and could not find Real images.

**Comment by whlzy** [comment]
We use the first 1M real image in CC3Ms to train a binary classifier, which can be downloaded [here](https://github.com/rom1504/img2dataset/blob/main/dataset_examples/cc3m.md).
![image](https://github.com/Inf-imagine/Sentry/assets/63985311/bf27e58c-7f2f-4ba8-921c-1db6bba422eb)
